# Generated by Django 3.1.4 on 2023-07-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bert',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
