# Generated by Django 3.0.6 on 2023-06-07 22:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0004_auto_20230607_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
