# Generated by Django 3.0.6 on 2023-06-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0007_auto_20230607_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='type_audit',
            field=models.CharField(blank=True, choices=[('HEADERS', 'Headers'), ('IMAGES', 'Images'), ('LINKS', 'Links')], max_length=20),
        ),
    ]
