# Generated by Django 3.1.4 on 2023-06-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0008_auto_20230607_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
