# Generated by Django 3.1.4 on 2023-06-07 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('extractor', '0009_auto_20230607_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractor',
            name='Org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='org.website'),
            preserve_default=False,
        ),
    ]
