# Generated by Django 3.1.4 on 2023-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalLinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internallinks',
            name='div',
        ),
        migrations.RemoveField(
            model_name='internallinks',
            name='script',
        ),
        migrations.AddField(
            model_name='internallinks',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
