---
version: '3.8'
services:

  bert-summary:
    image: osat/osat-contrib-bert-summary:latest
    container_name: ${NAMESPACE}-contrib-bert-summary
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TINI_VERSION: ${TINI_VERSION}
    environment:
    - BERT_SUMMARY_HOST=${BERT_SUMMARY_HOST}
    - BERT_SUMMARY_PORT=${BERT_SUMMARY_PORT}
    - BERT_SUMMARY_DEBUG=${BERT_SUMMARY_DEBUG}
    ports:
    - ${BERT_SUMMARY_PORT}:${BERT_SUMMARY_PORT}
    expose:
    - ${BERT_SUMMARY_PORT}
    labels:
    - "org.label-schema.group=extractor"
    - "traefik.enable=true"
    restart: unless-stopped
