# Generated by Django 3.0.6 on 2030-06-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lighthouse_Results',
            new_name='Lighthouse_Result',
        ),
    ]
