# Generated by Django 3.0.6 on 2023-06-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0006_auto_20230607_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lighthouse_result',
            name='result',
        ),
        migrations.AlterField(
            model_name='lighthouse_result',
            name='performance_score',
            field=models.TextField(max_length=10),
        ),
    ]
