# Generated by Django 3.1.4 on 2023-06-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0009_auto_20230607_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lighthouse',
            name='update_rate',
        ),
    ]
