# Generated by Django 3.1.4 on 2023-06-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0010_remove_lighthouse_update_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lighthouse',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
